### ISSUE TITLE
Issue with Package Name on SOTI 15.3

### ISSUE THREAD

**Issue by wh1tacr3** [mobilebob/Soti_Dynamic_Template#4]
On the latest version of SOTI (15.3) it no longer lets you have a space in the package name, so it won't except "HTML HEADER".  Is there a way to adjust this code to use a format that has no spaces in it. 

For example: "HTML-HEADER"

**Comment by mobilebob** [comment]
The new code I just committed allows for HTML-HEADER and HTML-FOOTER as well.  This should fix the issue your having with 15.3.
