### ISSUE TITLE
Inject Text at the top and inbetween lines of apps

### ISSUE THREAD

**Issue by xMacBethx** [mobilebob/Soti_Dynamic_Template#5]
We like to have the devices serial number available to our users at a glance so they can easily give that information when they have to call about an issue. This is what is entered currently, it is entered just above the row information.

	<div id="Main">
		<span class="Info">Serial#: %SERIALNUM%</span>
		<div class="row">

Do know of a way to enter that into your template?

**Comment by mobilebob** [comment]
Just add Serial#: %SERIALNUM% into the HTML-HEADER item.  % variables work within the Header and Footer items.

**Comment by xMacBethx** [comment]
Thanks for the quick response. What you mentioned does work but I was hoping to separate it from the Header and Footer. We have logos and text we plan on inserting in those locations. Is there a way to get the % variable to show in between as a basic text in between the Header and first row of icons?

One other problem we are having may be down to the device we are using, Pixel 6's, the icons are aligned to the left, is that purposeful? Is there a way to align them to be centered?

**Comment by mobilebob** [comment]
For the second row check out https://github.com/cryptogeek0610/Soti_Dynamic_Template_v2.0

For the Centering issue:
I don't have time to test to update the code here, but give this a try.  If it works well think about a pull request and I'll add it into the code.

That fork added a second header line and I think is what your looking for.
As for alignment try 

margin-left: auto;
margin-right: auto;

on the,
#Main .row ul li {
and
#Main .row ul li img {
Blocks.

https://www.w3.org/Style/Examples/007/center.en.tmpl
